// <auto-generated />
using System;
using Diversion;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diversion.Migrations
{
    [DbContext(typeof(DiversionDbContext))]
    [Migration("20251130163045_AddModelsAndSeedData")]
    partial class AddModelsAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diversion.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InterestTagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("RequiresRsvp")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestTagId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Diversion.Models.EventAttendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventAttendees");
                });

            modelBuilder.Entity("Diversion.Models.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Outdoor activities and wilderness adventures",
                            Name = "Outdoors & Adventure"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Video games, board games, and tabletop gaming",
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Model building, collecting, and hobbies",
                            Name = "Models & Collecting"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Physical activities and sports",
                            Name = "Fitness & Sports"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Creative and artistic pursuits",
                            Name = "Arts & Crafts"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Music performance and appreciation",
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Culinary arts and beverages",
                            Name = "Food & Drink"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Tech projects and programming",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Scientific research and medical topics",
                            Name = "Science & Medicine"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Sci-fi, fantasy, and speculative fiction",
                            Name = "Science Fiction & Fantasy"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "Woodworking and traditional crafts",
                            Name = "Woodworking & Craftsmanship"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "Cars, trucks, and heavy machinery",
                            Name = "Automotive & Machinery"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Description = "Books, writing, and storytelling",
                            Name = "Literature & Writing"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Description = "Combat sports and martial disciplines",
                            Name = "Martial Arts"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Description = "Pop culture, retro trends, and media",
                            Name = "Pop Culture & Nostalgia"
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Description = "Historical events and ancient civilizations",
                            Name = "History & Archaeology"
                        });
                });

            modelBuilder.Entity("Diversion.Models.SubInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.ToTable("SubInterests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            Description = "Trail hiking and backpacking",
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000002"),
                            Description = "Outdoor camping and survival",
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Camping"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000003"),
                            Description = "Indoor and outdoor climbing",
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Rock Climbing"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000004"),
                            Description = "Kayaking and canoeing",
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Kayaking"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000005"),
                            Description = "Off-road cycling",
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mountain Biking"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000006"),
                            Description = "River rafting and rapids navigation",
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "White Water Rafting"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000007"),
                            Description = "Bushcraft and wilderness survival skills",
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Primitive Survival"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000008"),
                            Description = "Wild edibles and mushroom hunting",
                            InterestId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Foraging"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Description = "Computer gaming",
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "PC Gaming"
                        },
                        new
                        {
                            Id = new Guid("b0000002-0000-0000-0000-000000000002"),
                            Description = "PlayStation, Xbox, Nintendo",
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Console Gaming"
                        },
                        new
                        {
                            Id = new Guid("b0000003-0000-0000-0000-000000000003"),
                            Description = "Strategy and party board games",
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = new Guid("b0000004-0000-0000-0000-000000000004"),
                            Description = "D&D, Pathfinder, and tabletop RPGs",
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "TTRPGs"
                        },
                        new
                        {
                            Id = new Guid("b0000005-0000-0000-0000-000000000005"),
                            Description = "TCGs, poker, and card games",
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Card Games"
                        },
                        new
                        {
                            Id = new Guid("b0000006-0000-0000-0000-000000000006"),
                            Description = "Classic consoles and arcade games",
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Retro Gaming"
                        },
                        new
                        {
                            Id = new Guid("b0000007-0000-0000-0000-000000000007"),
                            Description = "Video game speedrunning",
                            InterestId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Speedrunning"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000001"),
                            Description = "Gundam model kits and gunpla",
                            InterestId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Gundam"
                        },
                        new
                        {
                            Id = new Guid("c0000002-0000-0000-0000-000000000002"),
                            Description = "Model trains and railroading layouts",
                            InterestId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Model Trains"
                        },
                        new
                        {
                            Id = new Guid("c0000003-0000-0000-0000-000000000003"),
                            Description = "Scale model vehicles",
                            InterestId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Model Cars"
                        },
                        new
                        {
                            Id = new Guid("c0000004-0000-0000-0000-000000000004"),
                            Description = "Warhammer and tabletop minis",
                            InterestId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Miniature Painting"
                        },
                        new
                        {
                            Id = new Guid("c0000005-0000-0000-0000-000000000005"),
                            Description = "Remote control cars and drones",
                            InterestId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "RC Vehicles"
                        },
                        new
                        {
                            Id = new Guid("c0000006-0000-0000-0000-000000000006"),
                            Description = "Scale model planes and helicopters",
                            InterestId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Model Aircraft"
                        },
                        new
                        {
                            Id = new Guid("c0000007-0000-0000-0000-000000000007"),
                            Description = "Die-cast vehicle collections",
                            InterestId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Die-Cast Collecting"
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000001"),
                            Description = "Yoga and meditation",
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Yoga"
                        },
                        new
                        {
                            Id = new Guid("d0000002-0000-0000-0000-000000000002"),
                            Description = "Running and marathons",
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Running"
                        },
                        new
                        {
                            Id = new Guid("d0000003-0000-0000-0000-000000000003"),
                            Description = "Strength training and bodybuilding",
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Weightlifting"
                        },
                        new
                        {
                            Id = new Guid("d0000004-0000-0000-0000-000000000004"),
                            Description = "High-intensity functional fitness",
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "CrossFit"
                        },
                        new
                        {
                            Id = new Guid("d0000005-0000-0000-0000-000000000005"),
                            Description = "Swimming and aquatic sports",
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Swimming"
                        },
                        new
                        {
                            Id = new Guid("d0000006-0000-0000-0000-000000000006"),
                            Description = "Road and track cycling",
                            InterestId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Cycling"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0000-0000-0000-000000000001"),
                            Description = "Canvas and fine art painting",
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Painting"
                        },
                        new
                        {
                            Id = new Guid("e0000002-0000-0000-0000-000000000002"),
                            Description = "Sketching and illustration",
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Drawing"
                        },
                        new
                        {
                            Id = new Guid("e0000003-0000-0000-0000-000000000003"),
                            Description = "Digital and film photography",
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("e0000004-0000-0000-0000-000000000004"),
                            Description = "Ceramics and pottery",
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Pottery"
                        },
                        new
                        {
                            Id = new Guid("e0000005-0000-0000-0000-000000000005"),
                            Description = "Fiber arts and textile crafts",
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Knitting & Crochet"
                        },
                        new
                        {
                            Id = new Guid("e0000006-0000-0000-0000-000000000006"),
                            Description = "Digital illustration and design",
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Digital Art"
                        },
                        new
                        {
                            Id = new Guid("e0000007-0000-0000-0000-000000000007"),
                            Description = "Hand lettering and calligraphy",
                            InterestId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Calligraphy"
                        },
                        new
                        {
                            Id = new Guid("f0000001-0000-0000-0000-000000000001"),
                            Description = "Acoustic and electric guitar",
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Guitar"
                        },
                        new
                        {
                            Id = new Guid("f0000002-0000-0000-0000-000000000002"),
                            Description = "Piano and keyboard",
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Piano"
                        },
                        new
                        {
                            Id = new Guid("f0000003-0000-0000-0000-000000000003"),
                            Description = "DJ and electronic music",
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "DJing"
                        },
                        new
                        {
                            Id = new Guid("f0000004-0000-0000-0000-000000000004"),
                            Description = "Concert going and music events",
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Live Concerts"
                        },
                        new
                        {
                            Id = new Guid("f0000005-0000-0000-0000-000000000005"),
                            Description = "Audio production and recording",
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Music Production"
                        },
                        new
                        {
                            Id = new Guid("f0000006-0000-0000-0000-000000000006"),
                            Description = "Record collecting and turntables",
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Vinyl Collecting"
                        },
                        new
                        {
                            Id = new Guid("f0000007-0000-0000-0000-000000000007"),
                            Description = "Drumming and percussion instruments",
                            InterestId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Drums & Percussion"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000001"),
                            Description = "Home cooking and culinary arts",
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = new Guid("10000002-0000-0000-0000-000000000002"),
                            Description = "Baking and pastry",
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Baking"
                        },
                        new
                        {
                            Id = new Guid("10000003-0000-0000-0000-000000000003"),
                            Description = "Coffee brewing and appreciation",
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = new Guid("10000004-0000-0000-0000-000000000004"),
                            Description = "Beer tasting and brewing",
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Craft Beer"
                        },
                        new
                        {
                            Id = new Guid("10000005-0000-0000-0000-000000000005"),
                            Description = "Wine appreciation and oenology",
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Wine Tasting"
                        },
                        new
                        {
                            Id = new Guid("10000006-0000-0000-0000-000000000006"),
                            Description = "Sourdough baking and fermentation",
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Sourdough Bread"
                        },
                        new
                        {
                            Id = new Guid("10000007-0000-0000-0000-000000000007"),
                            Description = "BBQ techniques and meat smoking",
                            InterestId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "BBQ & Smoking"
                        },
                        new
                        {
                            Id = new Guid("20000001-0000-0000-0000-000000000001"),
                            Description = "Software development and coding",
                            InterestId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Programming"
                        },
                        new
                        {
                            Id = new Guid("20000002-0000-0000-0000-000000000002"),
                            Description = "3D printing and modeling",
                            InterestId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "3D Printing"
                        },
                        new
                        {
                            Id = new Guid("20000003-0000-0000-0000-000000000003"),
                            Description = "Electronics and circuit building",
                            InterestId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("20000004-0000-0000-0000-000000000004"),
                            Description = "Robot building and automation",
                            InterestId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Robotics"
                        },
                        new
                        {
                            Id = new Guid("20000005-0000-0000-0000-000000000005"),
                            Description = "AI, ML, and data science",
                            InterestId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "AI & Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("20000006-0000-0000-0000-000000000006"),
                            Description = "InfoSec and ethical hacking",
                            InterestId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = new Guid("20000007-0000-0000-0000-000000000007"),
                            Description = "Home servers and networking",
                            InterestId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Homelab"
                        },
                        new
                        {
                            Id = new Guid("30000001-0000-0000-0000-000000000001"),
                            Description = "Medical news and breakthrough research",
                            InterestId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Medical Research"
                        },
                        new
                        {
                            Id = new Guid("30000002-0000-0000-0000-000000000002"),
                            Description = "Space, stars, and celestial phenomena",
                            InterestId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Astronomy"
                        },
                        new
                        {
                            Id = new Guid("30000003-0000-0000-0000-000000000003"),
                            Description = "Theoretical and applied physics",
                            InterestId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Physics"
                        },
                        new
                        {
                            Id = new Guid("30000004-0000-0000-0000-000000000004"),
                            Description = "Life sciences and ecosystems",
                            InterestId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Biology & Ecology"
                        },
                        new
                        {
                            Id = new Guid("30000005-0000-0000-0000-000000000005"),
                            Description = "Chemical reactions and compounds",
                            InterestId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = new Guid("30000006-0000-0000-0000-000000000006"),
                            Description = "Brain research and cognitive science",
                            InterestId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Neuroscience"
                        },
                        new
                        {
                            Id = new Guid("30000007-0000-0000-0000-000000000007"),
                            Description = "DNA, heredity, and genetic engineering",
                            InterestId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Genetics"
                        },
                        new
                        {
                            Id = new Guid("40000001-0000-0000-0000-000000000001"),
                            Description = "Time travel theory and paradoxes",
                            InterestId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Time Travel"
                        },
                        new
                        {
                            Id = new Guid("40000002-0000-0000-0000-000000000002"),
                            Description = "Zombie apocalypse and survival",
                            InterestId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Zombies"
                        },
                        new
                        {
                            Id = new Guid("40000003-0000-0000-0000-000000000003"),
                            Description = "Star Wars, Star Trek, and space epics",
                            InterestId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Space Opera"
                        },
                        new
                        {
                            Id = new Guid("40000004-0000-0000-0000-000000000004"),
                            Description = "Dystopian tech futures",
                            InterestId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            Id = new Guid("40000005-0000-0000-0000-000000000005"),
                            Description = "High fantasy and world-building",
                            InterestId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Fantasy Worlds"
                        },
                        new
                        {
                            Id = new Guid("40000006-0000-0000-0000-000000000006"),
                            Description = "Extraterrestrial life and phenomena",
                            InterestId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Aliens & UFOs"
                        },
                        new
                        {
                            Id = new Guid("40000007-0000-0000-0000-000000000007"),
                            Description = "What-if scenarios and alternate timelines",
                            InterestId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Alternate History"
                        },
                        new
                        {
                            Id = new Guid("40000008-0000-0000-0000-000000000008"),
                            Description = "End-of-world scenarios and survival",
                            InterestId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Post-Apocalyptic"
                        },
                        new
                        {
                            Id = new Guid("50000001-0000-0000-0000-000000000001"),
                            Description = "Custom furniture and cabinetry",
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Furniture Making"
                        },
                        new
                        {
                            Id = new Guid("50000002-0000-0000-0000-000000000002"),
                            Description = "Lathe work and bowl turning",
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Wood Turning"
                        },
                        new
                        {
                            Id = new Guid("50000003-0000-0000-0000-000000000003"),
                            Description = "Exotic woods and lumber identification",
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Wood Species"
                        },
                        new
                        {
                            Id = new Guid("50000004-0000-0000-0000-000000000004"),
                            Description = "Wood carving and whittling",
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Carving"
                        },
                        new
                        {
                            Id = new Guid("50000005-0000-0000-0000-000000000005"),
                            Description = "Traditional joinery techniques",
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Joinery"
                        },
                        new
                        {
                            Id = new Guid("50000006-0000-0000-0000-000000000006"),
                            Description = "Stains, oils, and finishing techniques",
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Wood Finishing"
                        },
                        new
                        {
                            Id = new Guid("50000007-0000-0000-0000-000000000007"),
                            Description = "Traditional hand tool woodworking",
                            InterestId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Hand Tools"
                        },
                        new
                        {
                            Id = new Guid("60000001-0000-0000-0000-000000000001"),
                            Description = "Vintage and classic automobiles",
                            InterestId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Classic Cars"
                        },
                        new
                        {
                            Id = new Guid("60000002-0000-0000-0000-000000000002"),
                            Description = "Pickup trucks and 4x4 vehicles",
                            InterestId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Trucks & Off-Road"
                        },
                        new
                        {
                            Id = new Guid("60000003-0000-0000-0000-000000000003"),
                            Description = "Vehicle restoration and rebuilding",
                            InterestId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Auto Restoration"
                        },
                        new
                        {
                            Id = new Guid("60000004-0000-0000-0000-000000000004"),
                            Description = "American muscle and performance cars",
                            InterestId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Muscle Cars"
                        },
                        new
                        {
                            Id = new Guid("60000005-0000-0000-0000-000000000005"),
                            Description = "Motorcycles and bike culture",
                            InterestId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Motorcycles"
                        },
                        new
                        {
                            Id = new Guid("60000006-0000-0000-0000-000000000006"),
                            Description = "Heavy machinery and construction vehicles",
                            InterestId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Construction Equipment"
                        },
                        new
                        {
                            Id = new Guid("60000007-0000-0000-0000-000000000007"),
                            Description = "Performance tuning and modification",
                            InterestId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Car Tuning"
                        },
                        new
                        {
                            Id = new Guid("60000008-0000-0000-0000-000000000008"),
                            Description = "Japanese domestic market vehicles",
                            InterestId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "JDM Culture"
                        },
                        new
                        {
                            Id = new Guid("70000001-0000-0000-0000-000000000001"),
                            Description = "Sci-fi literature and authors",
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("70000002-0000-0000-0000-000000000002"),
                            Description = "Epic fantasy and world-building",
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Fantasy Novels"
                        },
                        new
                        {
                            Id = new Guid("70000003-0000-0000-0000-000000000003"),
                            Description = "Detective fiction and suspense",
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Mystery & Thriller"
                        },
                        new
                        {
                            Id = new Guid("70000004-0000-0000-0000-000000000004"),
                            Description = "Horror fiction and gothic literature",
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("70000005-0000-0000-0000-000000000005"),
                            Description = "Poetry reading and writing",
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = new Guid("70000006-0000-0000-0000-000000000006"),
                            Description = "Canonical and classic works",
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Classic Literature"
                        },
                        new
                        {
                            Id = new Guid("70000007-0000-0000-0000-000000000007"),
                            Description = "Sequential art and graphic novels",
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Manga & Comics"
                        },
                        new
                        {
                            Id = new Guid("70000008-0000-0000-0000-000000000008"),
                            Description = "Fiction writing and storytelling",
                            InterestId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Creative Writing"
                        },
                        new
                        {
                            Id = new Guid("80000001-0000-0000-0000-000000000001"),
                            Description = "BJJ grappling and ground fighting",
                            InterestId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Brazilian Jiu-Jitsu"
                        },
                        new
                        {
                            Id = new Guid("80000002-0000-0000-0000-000000000002"),
                            Description = "Thai boxing and kickboxing",
                            InterestId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Muay Thai"
                        },
                        new
                        {
                            Id = new Guid("80000003-0000-0000-0000-000000000003"),
                            Description = "Traditional karate styles",
                            InterestId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Karate"
                        },
                        new
                        {
                            Id = new Guid("80000004-0000-0000-0000-000000000004"),
                            Description = "Korean martial art and Olympic sport",
                            InterestId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Taekwondo"
                        },
                        new
                        {
                            Id = new Guid("80000005-0000-0000-0000-000000000005"),
                            Description = "Israeli self-defense system",
                            InterestId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Krav Maga"
                        },
                        new
                        {
                            Id = new Guid("80000006-0000-0000-0000-000000000006"),
                            Description = "Western boxing and pugilism",
                            InterestId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Boxing"
                        },
                        new
                        {
                            Id = new Guid("80000007-0000-0000-0000-000000000007"),
                            Description = "Chinese martial arts styles",
                            InterestId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Kung Fu"
                        },
                        new
                        {
                            Id = new Guid("80000008-0000-0000-0000-000000000008"),
                            Description = "Mixed martial arts and UFC",
                            InterestId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "MMA"
                        },
                        new
                        {
                            Id = new Guid("90000001-0000-0000-0000-000000000001"),
                            Description = "1980s movies, music, and trends",
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "80s Pop Culture"
                        },
                        new
                        {
                            Id = new Guid("90000002-0000-0000-0000-000000000002"),
                            Description = "1990s pop culture and nostalgia",
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "90s Nostalgia"
                        },
                        new
                        {
                            Id = new Guid("90000003-0000-0000-0000-000000000003"),
                            Description = "Japanese animation and culture",
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Anime"
                        },
                        new
                        {
                            Id = new Guid("90000004-0000-0000-0000-000000000004"),
                            Description = "Marvel, DC, and indie comics",
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Comic Books"
                        },
                        new
                        {
                            Id = new Guid("90000005-0000-0000-0000-000000000005"),
                            Description = "Toy collecting and vintage figures",
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Action Figures"
                        },
                        new
                        {
                            Id = new Guid("90000006-0000-0000-0000-000000000006"),
                            Description = "Vintage computers and electronics",
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Retro Tech"
                        },
                        new
                        {
                            Id = new Guid("90000007-0000-0000-0000-000000000007"),
                            Description = "VHS tapes and physical media collecting",
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "VHS & Physical Media"
                        },
                        new
                        {
                            Id = new Guid("90000008-0000-0000-0000-000000000008"),
                            Description = "Arcade machines and pinball",
                            InterestId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Arcade Culture"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000001"),
                            Description = "Roman Empire and civilization",
                            InterestId = new Guid("10101010-1010-1010-1010-101010101010"),
                            Name = "Ancient Rome"
                        },
                        new
                        {
                            Id = new Guid("a1000002-0000-0000-0000-000000000002"),
                            Description = "Middle Ages and feudalism",
                            InterestId = new Guid("10101010-1010-1010-1010-101010101010"),
                            Name = "Medieval History"
                        },
                        new
                        {
                            Id = new Guid("a1000003-0000-0000-0000-000000000003"),
                            Description = "WWII history and battles",
                            InterestId = new Guid("10101010-1010-1010-1010-101010101010"),
                            Name = "World War II"
                        },
                        new
                        {
                            Id = new Guid("a1000004-0000-0000-0000-000000000004"),
                            Description = "Egyptian civilization and archaeology",
                            InterestId = new Guid("10101010-1010-1010-1010-101010101010"),
                            Name = "Ancient Egypt"
                        },
                        new
                        {
                            Id = new Guid("a1000005-0000-0000-0000-000000000005"),
                            Description = "Norse culture and Viking Age",
                            InterestId = new Guid("10101010-1010-1010-1010-101010101010"),
                            Name = "Vikings"
                        },
                        new
                        {
                            Id = new Guid("a1000006-0000-0000-0000-000000000006"),
                            Description = "Civil War history and reenactment",
                            InterestId = new Guid("10101010-1010-1010-1010-101010101010"),
                            Name = "American Civil War"
                        },
                        new
                        {
                            Id = new Guid("a1000007-0000-0000-0000-000000000007"),
                            Description = "Archaeological discoveries and digs",
                            InterestId = new Guid("10101010-1010-1010-1010-101010101010"),
                            Name = "Archaeology"
                        },
                        new
                        {
                            Id = new Guid("a1000008-0000-0000-0000-000000000008"),
                            Description = "Cold War era and espionage",
                            InterestId = new Guid("10101010-1010-1010-1010-101010101010"),
                            Name = "Cold War"
                        });
                });

            modelBuilder.Entity("Diversion.Models.UserInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubInterestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubInterestId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserId", "SubInterestId")
                        .IsUnique();

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("Diversion.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Diversion.Models.Event", b =>
                {
                    b.HasOne("Diversion.Models.SubInterest", "InterestTag")
                        .WithMany("Events")
                        .HasForeignKey("InterestTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterestTag");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Diversion.Models.EventAttendee", b =>
                {
                    b.HasOne("Diversion.Models.Event", "Event")
                        .WithMany("Attendees")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diversion.Models.SubInterest", b =>
                {
                    b.HasOne("Diversion.Models.Interest", "Interest")
                        .WithMany("SubInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("Diversion.Models.UserInterest", b =>
                {
                    b.HasOne("Diversion.Models.SubInterest", "SubInterest")
                        .WithMany("UserInterests")
                        .HasForeignKey("SubInterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diversion.Models.UserProfile", null)
                        .WithMany("UserInterests")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("SubInterest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diversion.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("Diversion.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diversion.Models.Event", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("Diversion.Models.Interest", b =>
                {
                    b.Navigation("SubInterests");
                });

            modelBuilder.Entity("Diversion.Models.SubInterest", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("Diversion.Models.UserProfile", b =>
                {
                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
